spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_schema: assessment
        jdbc:
          lob:
            non_contextual_creation: true
      hbm2ddl:
        auto: none
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/assessment?currentSchema=assessment
    username: postgres
    password: 12345
    initialization-mode: always
  hibernate:
    jpa:
    hbm2ddl: update
server:
  port: 8082
